name = "Telkit VI"
author = "Nosiphus"
version = "2026.04.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f78ed4a8e6e7b7848e814d5c6972bf77b6d35cde25d92f56af6498876e7da97"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.226"

[options]
acceptable-game-versions = ["1.21"]
