name = "Telkit VI"
author = "Nosiphus"
version = "2026.09.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa82b23b829e231ddd6b4508bf861024a15fbf680f76cef3a53dcf9c283eada1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"

[options]
acceptable-game-versions = ["1.21"]
