name = "Telkit Development Edition"
author = "Nosiphus"
version = "2026.03.07"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b15b7cb99857f241db7fc19556848084f7d0ea061c6af07348007e94e5b2090"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21"]
