name = "Telkit III"
author = "Nosiphus"
version = "2026.06.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47a2795d83a6929a3a165bf6677cb2ac9772d9e0995e59750cb87322d1f825a3"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.2", "1.16.3", "1.16.4"]
