name = "Telkit V"
author = "Nosiphus"
version = "2026.05.08"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acae221423d2e56059073218e7e5d49c11d4f17104ebab1c5b7a3e490db2001a"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
