name = "Telkit V"
author = "Nosiphus"
version = "2026.06.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "925a3e852d0b6ae807b895ccadbd82e25670870c5239cf50750bc4fa655c89b8"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
