name = "Telkit V"
author = "Nosiphus"
version = "2026.04.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c0d81c014578cb71d99d831c21d177bcfefd37d426bf4e25c9d64729938b5eb"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
