name = "Telkit I"
author = "Nosiphus"
version = "2026.05.28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd8c15afae57aa27e4e5e54b766acb514cf2262d9659b22dcbd882b7ffafb0b5"

[versions]
forge = "10.13.4.1614"
liteloader = "1.7.10_04"
minecraft = "1.7.10"
