name = "Aeronautics Server Pack"
author = "Nosiphus"
version = "2026.07.02"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17713a18cd9005faaf6e6ae2cd859ba384b465b018d923fdf3c3b12da6b72227"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
acceptable-game-versions = ["1.21"]
