name = "Aeronautics Server Pack"
author = "Nosiphus"
version = "2026.07.09"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98c39f79211977e379342046c0499c83cdaef56167a6ba4d4fe38d1ebc2eebf1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
acceptable-game-versions = ["1.21"]
