name = "Minecraft TTF Font"
filename = "MinecraftTTFFont.zip"
side = "client"

[download]
url = "https://drive.usercontent.google.com/u/0/uc?id=1tzKkrpe0ijQthmWAhTYIyL1H-IDFf6wG&export=download"
hash-format = "sha1"
hash = "763694fb74374d356cce0f5e771aa48e485c68af"