name = "Nosiphus Vanilla+"
author = "Nosiphus"
version = "2026.04.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1858ee4e8b98ac8eb6377a6a23ccca734e9fe755b3d5ae16d41464c60b568222"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1.1", "26.1"]
