name = "Nosiphus Vanilla+"
author = "Nosiphus"
version = "2026.04.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17a3c29ab5e78f4bac90efecd86b7ee16ada6bbac5a8e533b6f27a2591950a4e"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1.1", "26.1"]
