name = "Nosiphus Pack o' Fun"
author = "Nosiphus"
version = "2026.03.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c096ce8bbb7bcc02a9a7ec52183ffec9fb19d7c017c4374bb18af8065911a22"

[versions]
forge = "6.6.2.534"
minecraft = "1.4.7"

[options]
acceptable-game-versions = ["1.4.6"]
