name = "NosPack"
author = "Nosiphus"
version = "2026.03.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c1fbbdd76d5d2f2f6b6febef26ac565705b50d1c5de913c671b8589a87255b7"

[versions]
forge = "9.11.1.1345"
liteloader = "1.6.4_01"
minecraft = "1.6.4"
