name = "Telkit IV"
author = "Nosiphus"
version = "2026.07.29"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cf492511c8279e7f1eb93e894668124c5497b235367c89c8c1164186bda4639"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
