name = "Telkit IV"
author = "Nosiphus"
version = "2026.06.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89d1c12c240083b16bf693949a185cca44e7590cdf0c88ae88505b033c1cfdf5"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
