name = "Telkit IV"
author = "Nosiphus"
version = "2026.07.29"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f2e9abfa56dd73b95758d5569eb460e651fbafe704350961f49140b722d02c1"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
