name = "Nosiphus Required Mods"
author = "Nosiphus"
version = "2026.03.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96939d311e6e68d31da1c7f8cb2ea542edb5b9e17c82bead8db9fd72fd492479"

[versions]
forge = "7.8.1.738"
minecraft = "1.5.2"
