name = "Nosiphus Required Mods"
author = "Nosiphus"
version = "2026.03.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b5a3f4727dfb0b64fcc366f9b3a2415426bf2c773e2214e5bae702967a0c2c1"

[versions]
forge = "7.8.1.738"
minecraft = "1.5.2"
