name = "Telkit II"
author = "Nosiphus"
version = "2026.09.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71c38be0a886a6a94cef7a57405741a93fdd22535a2006cfb018d3f2a8410e77"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"

[options]
acceptable-game-versions = ["1.12", "1.12.1"]
