name = "Telkit II"
author = "Nosiphus"
version = "2026.09.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2badaf390d9bc118990507a6d318aabd5b5814b999e913714b99b8a9b64f8d0a"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"

[options]
acceptable-game-versions = ["1.12", "1.12.1"]
