name = "Telkit II"
author = "Nosiphus"
version = "2026.06.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cf7953b9bbaa45031ee464476e51dfe9ca3eed4da738e05f2ac888b0de5898d"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"

[options]
acceptable-game-versions = ["1.12", "1.12.1"]
