name = "Maguire's Apocalypse"
author = "Nosiphus"
version = "2026.07.29"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab37752ee994f5426c5363e62c6c5242074c9d9e87d7a80fb3de92734be592c4"

[versions]
forge = "10.13.4.1614"
liteloader = "1.7.10_04"
minecraft = "1.7.10"
